name: carp_mobile_sensing
description: Mobile Sensing Framework for Flutter. A software framework for collecting sensor data from the phone and attached wearable devices via probes. Can be extended.
version: 0.6.3
author:  CACHET Team <cph.cachet@gmail.com>
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/carp_mobile_sensing


environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # utility plugins
  system_info: ^0.1.0
  uuid: ^2.0.0
  async: ^2.0.8
  device_info: ^0.4.0
  json_annotation: ^3.0.0
  path_provider: ^1.2.0
  archive: ^2.0.4
  #permission_handler: ^4.0.0
  permission_handler:
    path: ../permission_handler/

  # probe-dependent plugins
  sensors: ^0.4.0
  battery: ^0.3.0
  stats: ^0.2.0           # For calculating statistics, ex LightProbe

  # the CACHET plugins
  pedometer: ^1.0.0       # Get the step count from local OS
  light: ^0.1.0           # Light sensor over platform channel
  device_apps: ^1.0.8     # Device installed apps over platform channel
  screen_state: ^0.1.0    # Screen LOCK/ON/OFF
  app_usage: ^0.1.0       # App-usage statistics

#dependency_overrides:
#  permission_handler:
#    path: ../permission_handler/

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable: ^3.0.0
  test:


# The following section is specific to Flutter.
flutter:

